name: Copy updated Intro and Example files to bookdown repo

# only run this workflow when the _Intro or _Examples files have changed
on: 
  push:
    branches: 
      - main
    paths:
      - '[0-9]+-[0-1]_**.*md'

jobs:
  copy_intro_file_to_bookdown: 
    runs-on: ubuntu-latest
    steps:
    # check out weekly materials project
    - name: Check out weekly materials project
      uses: actions/checkout@v3
    # check out bookdown project using token generated in that project to successfully access it from inside the Notehub GitHub Action workflow
    - name: Check out bookdown project
      uses: actions/checkout@v3
      with:
        repository: VT-BSE3144/bookdown
        path: ./bookdown
        token: ${{ secrets.BOOKDOWN_TOKEN }}
    # make a copy of the intro and examples files from the weekly materials project
    - name: Copy Intro and Example files
      run: bash ./.github/scripts/copy-intro-example-files.sh
      env:
        DESTINATION_PATH: ./bookdown/
    # make a branch in notehub-js repo and push the copy of the openapi file there
    - name: Push to bookdown repo
      run: bash ./.github/scripts/push-materials-to-bookdown.sh
      env:
        BRANCH: main